name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Clean
      run: xcodebuild clean -scheme RickAndMortyApp -sdk iphonesimulator

    - name: Build
      run: xcodebuild build -scheme RickAndMortyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'

    - name: Run tests
      run: xcodebuild test -scheme RickAndMortyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
