name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout RickAndMortyApp
      uses: actions/checkout@v3
      with:
        path: RickAndMortyApp

    - name: Checkout CharacterKit
      uses: actions/checkout@v3
      with:
        # Replace with your actual CharacterKit repository
        repository: yourusername/CharacterKit
        path: CharacterKit

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Clean Build Test
      working-directory: RickAndMortyApp
      run: |
        xcodebuild clean build test \
          -scheme RickAndMortyApp \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          SWIFT_PACKAGE_PATHS="tesddev/CharacterKitPackage"
